### ISSUE TITLE
add icon for each topic

### ISSUE THREAD

**Issue by AimeTPGM** [AimeTPGM/traxing#10]
add icon for each topic

<img width="1680" alt="Screen Shot 2563-10-24 at 02 39 17" src="https://user-images.githubusercontent.com/5433758/97048766-c6db1b00-15a4-11eb-9112-f0aaf8be08ec.png">

- Education
- Economic
- Agriculture
- Medical
- Transportation
- Technology
- Environment
- Country's Security
- Social Justice

respectively

**Comment by hyunjiLeeTech** [comment]
Hi, can you please assign me to this issue? I would like to work on this task. Thanks.

**Comment by AimeTPGM** [comment]
@hyunjiLeeTech yes sure :)

**Comment by hyunjiLeeTech** [comment]
Please close this issue. The pull request for this issue was merged (url: https://github.com/AimeTPGM/traxing/pull/17, commit: '1236389')
